# publish.yml

name: 'Publish'
env:
  USERNAME: maxakuru
  IMAGE: git-backup
  TAG: latest
  TEST_TAG: test
on:
  push:
    branches: 
      - main
jobs:
  publish:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build test image
        run: docker build . --file Dockerfile --tag $USERNAME/$IMAGE:$TEST_TAG
      - name: Test image
        env: 
          USERNAME: ${{ env.USERNAME }}
          TAG: ${{ env.TEST_TAG }}
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./test/functional/test.sh
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE }}:${{ env.TAG }}