# publish.yml

name: 'Publish'
env:
  USER: maxakuru
  IMAGE: git-backup
  TAG: latest
  TEST_TAG: test
on:
  push:
    branches: 
      - main
jobs:
  publish:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build test image
        run: docker build . --file Dockerfile --tag $USER/$IMAGE:$TEST_TAG
      - name: Test image
        env: 
          TAG: ${{ env.TEST_TAG }}
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./test/functional/test.sh
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: $USER/$IMAGE:$TAG