# test.yml
name: 'Test'
env:
  USER: maxakuru
  IMAGE: git-backup
on:
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $USER/$IMAGE:$(date +%s)
      - name: Test Docker image
        env: 
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./test/functional/test.sh
        shell: bash