# test.yml
name: 'Test'
env:
  USERNAME: maxakuru
  IMAGE: git-backup
on:
  pull_request:
    branches: 
      - main
jobs:
  build:
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo "::set-output name=TAG::$(date +%s)"
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $USERNAME/$IMAGE:${{ steps.tag.outputs.TAG }}
      - name: Test Docker image
        env: 
          USERNAME: ${{ env.USERNAME }}
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.tag.outputs.TAG }}
        run: ./test/functional/test.sh
        shell: bash